# Generated by Django 4.2.4 on 2023-08-16 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sirais_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='coach',
            field=models.ForeignKey(default=None, limit_choices_to={'groups__name': 'Coachs'}, on_delete=django.db.models.deletion.CASCADE, related_name='projets_coach', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
