# Generated by Django 4.2.4 on 2023-08-18 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sirais_app', '0002_alter_project_coach_alter_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='description',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='name',
        ),
        migrations.AddField(
            model_name='resource',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resource',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='resource',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('document', 'Document'), ('image', 'Image'), ('lien', 'Lien')], default='document', max_length=100),
        ),
        migrations.AddField(
            model_name='resource',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='coach',
            field=models.ForeignKey(default='Choisir un coach', limit_choices_to={'groups__name': 'Coachs'}, on_delete=django.db.models.deletion.CASCADE, related_name='projets_coach', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='porteur_de_projet',
            field=models.ForeignKey(default='Choisir un porteur de projet', limit_choices_to={'groups__name': 'Porteurs de projet'}, on_delete=django.db.models.deletion.CASCADE, related_name='projets_porteur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='sirais_app.project'),
        ),
    ]
