# Generated by Django 4.2.4 on 2023-08-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirais_app', '0004_resource_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
