# Generated by Django 4.2.4 on 2023-08-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirais_app', '0006_project_current_phase_resource_validation_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='validation_phase',
            field=models.CharField(choices=[('ideation', 'Idéation'), ('prototypage', 'Prototypage'), ('modele_economique', 'Modèle économique'), ('entree_marche', 'Entrée sur le marché')], default='ideation', max_length=20),
        ),
    ]
