# Generated by Django 4.2.4 on 2023-08-25 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sirais_app', '0007_alter_resource_validation_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessModelCanvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_segment', models.TextField()),
                ('value_proposition', models.TextField()),
                ('channels', models.TextField()),
                ('customer_relation', models.TextField()),
                ('money_source', models.TextField()),
                ('key_resource', models.TextField()),
                ('key_activities', models.TextField()),
                ('key_partners', models.TextField()),
                ('money_structure', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sirais_app.project')),
            ],
        ),
    ]
