# Generated by Django 4.2.4 on 2023-08-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirais_app', '0009_remove_task_due_date_remove_task_progress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='company',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mentor_expertise',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mentor_photo',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='expertise',
            field=models.CharField(max_length=200),
        ),
    ]
