# Generated by Django 4.2.4 on 2023-09-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirais_app', '0010_remove_customuser_bio_remove_customuser_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='state_date',
        ),
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
