# Generated by Django 4.2.4 on 2023-09-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sirais_app', '0013_customuser_groups_customuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default=None, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='expertise',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='permission',
            field=models.ManyToManyField(related_name='users', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default='img/default_coach.jpg', upload_to='img_coachProfile', verbose_name='photo de profil'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='users_group', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
