# Generated by Django 4.2.4 on 2023-09-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirais_app', '0022_remove_customuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, default='Votre adresse par défaut', max_length=200, null=True),
        ),
    ]
