# Generated by Django 4.2.4 on 2023-09-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirais_app', '0025_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='expertise',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
