# Generated by Django 4.2.4 on 2023-09-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirais_app', '0026_alter_customuser_expertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
