# Generated by Django 4.2.4 on 2023-09-26 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sirais_app', '0027_customuser_password_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='password_2',
        ),
        migrations.AlterField(
            model_name='project',
            name='porteur_de_projet',
            field=models.ForeignKey(default='Choisir un porteur de projet', limit_choices_to={'groups__name': 'Porteur de projet'}, on_delete=django.db.models.deletion.CASCADE, related_name='projets_porteur', to=settings.AUTH_USER_MODEL),
        ),
    ]
