# Generated by Django 4.2.4 on 2023-10-21 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sirais_app', '0028_remove_customuser_password_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectownerprojectassignment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectownerprojectassignment',
            name='project_owner',
        ),
        migrations.DeleteModel(
            name='CoachProjectAssignment',
        ),
        migrations.DeleteModel(
            name='ProjectOwnerProjectAssignment',
        ),
    ]
