# Generated by Django 4.2.4 on 2023-10-27 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sirais_app', '0032_task_start_date_alter_task_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
    ]
