# Generated by Django 4.2.4 on 2023-10-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirais_app', '0034_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='members', to='sirais_app.project'),
        ),
    ]
