# Generated by Django 4.2.4 on 2023-10-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirais_app', '0035_customuser_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='biographie',
            field=models.TextField(blank=True, default=None),
        ),
    ]
