# Generated by Django 4.2.4 on 2023-10-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirais_app', '0044_remove_customuser_biographie'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='biographie',
            field=models.TextField(default=''),
        ),
    ]
