# Generated by Django 4.2.4 on 2023-11-03 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sirais_app', '0051_remove_customuser_projects_customuser_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmodelcanvas',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sirais_app.project'),
        ),
    ]
