# Generated by Django 4.2.4 on 2023-11-07 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sirais_app', '0052_alter_businessmodelcanvas_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessmodelcanvas',
            old_name='channels',
            new_name='activites_cles',
        ),
        migrations.RenameField(
            model_name='businessmodelcanvas',
            old_name='customer_relation',
            new_name='cannaux_de_distribution',
        ),
        migrations.RenameField(
            model_name='businessmodelcanvas',
            old_name='key_activities',
            new_name='partenaires_cles',
        ),
        migrations.RenameField(
            model_name='businessmodelcanvas',
            old_name='key_resource',
            new_name='proposition_de_valeur',
        ),
        migrations.RenameField(
            model_name='businessmodelcanvas',
            old_name='key_partners',
            new_name='relation_client',
        ),
        migrations.RenameField(
            model_name='businessmodelcanvas',
            old_name='key_segment',
            new_name='ressources_cles',
        ),
        migrations.RenameField(
            model_name='businessmodelcanvas',
            old_name='money_source',
            new_name='segment_client',
        ),
        migrations.RenameField(
            model_name='businessmodelcanvas',
            old_name='money_structure',
            new_name='source_de_revenus',
        ),
        migrations.RenameField(
            model_name='businessmodelcanvas',
            old_name='value_proposition',
            new_name='structure_des_couts',
        ),
    ]
