# Generated by Django 4.2.4 on 2023-11-07 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sirais_app', '0053_rename_channels_businessmodelcanvas_activites_cles_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Informations du projet'},
        ),
    ]
